Analytics labels and client appointment history on client page
anapiyani/Crm pull request #215
Opened 2024-09-19 10:43 UTC by Yangdux

2024-09-24 11:47 UTC, anapiyani commented on src/pages/analytics/analytics.tsx
>            }
Boxes to div

2024-09-24 11:47 UTC, anapiyani commented on src/pages/analytics/styles.module.scss
> +//   background-color: #fff;
delete all coments

2024-09-24 11:48 UTC, anapiyani commented on src/pages/analytics/analytics.tsx
> +//         />
delete comments

2024-09-24 11:48 UTC, anapiyani commented on src/pages/analytics/analytics.tsx
> +                  {imageDescriptions["average_transaction.png"]}
typegraphgy to <p>

2024-09-24 12:43 UTC, anapiyani commented on src/pages/clients/client-card/components/visit-history-table.tsx
>          />
Please do not use ChatGpt

2024-09-28 13:24 UTC, anapiyani commented on src/components/search-filter-card/search-filter-card.tsx
> +// export default SearchFilterCard;
delete comments

2024-09-28 13:24 UTC, anapiyani commented on src/components/search-filter-card/search-filter-card.tsx
> +  }, [open]);
delete comments

2024-09-28 13:24 UTC, anapiyani commented on src/components/search-filter-card/search-filter-card.tsx
> -  const [isEnable] = useState(openEnabled);
add types??????????

2024-09-28 13:24 UTC, anapiyani commented on src/components/search-filter-card/search-filter-card.tsx
> +  openEnabled = true, // defaults to being toggleable if not specified
delete comments

2024-09-28 13:25 UTC, anapiyani commented on src/components/search-filter-card/styles.module.scss
> +  }
delete comments

2024-09-28 13:26 UTC, anapiyani commented on src/pages/analytics/analytics.tsx
>      "https://firebasestorage.googleapis.com/v0/b/wonkai-addb2.appspot.com/o/superwise%2Ftotal_before_discounts.png?alt=media&token=a5f62f86-93f9-4280-9ef1-e684a96249f7",
delete space {download prettier and enable the function prettier after saving ur code sucks dude}

2024-09-28 13:27 UTC, anapiyani commented on src/pages/clients/client-card/client-card.page.tsx
> +  // const [page, setPage] = useState(1);
Why comment?????

2024-09-28 13:27 UTC, anapiyani commented on src/pages/clients/client-card/client-card.page.tsx
> +  const [pageSize, setPageSize] = useState(5);
Where is types for UseStates????

2024-09-28 13:27 UTC, anapiyani commented on src/pages/clients/client-card/client-card.page.tsx
> +        .reduce((total, service) => total + parseFloat(service.total_price), 0) + " ₸",
again comments

2024-09-28 13:27 UTC, anapiyani commented on src/pages/clients/client-card/client-card.page.tsx
> +
comments

2024-09-28 13:29 UTC, anapiyani commented on src/pages/employees/salary/_components/step-input/step-input.component.tsx
> +      <p style={labelLength}>{labelName}</p>
wrong :
style={labelLength}
should be:
labelLength && (style={labelLength})

to be sure that labelLength is not null or undefinted

2024-09-28 13:30 UTC, anapiyani commented on src/pages/index.ts
> +import InventoryPage from "./storage/accounting/storage-accounting.page";
SO TMRW ASK ME
1. SO... FIST PAGES SHOULD BE EXPORTED IN INDEX.TS IN PAGES FOLDER

2024-09-28 13:30 UTC, anapiyani commented on src/pages/login/_components/email/email.page.tsx
>                id="outlined-basic"
WHY COMMENTS?

2024-09-28 13:31 UTC, anapiyani commented on src/pages/login/_components/email/email.page.tsx
> +              autoComplete="new-password" // important for disabling autofill
COMMENT AGAIN

2024-09-28 13:31 UTC, anapiyani commented on src/pages/storage/accounting/_components/chart1/chart-inventory.tsx
> +  data: any[];
ANY? never use any, write types for them.

2024-09-28 13:32 UTC, anapiyani commented on src/pages/storage/accounting/_components/chart1/chart-inventory.tsx
> +  const [showActiveDiscounts, setShowActiveDiscounts] = useState(true);
SO BASICLY TSX MEANS TYPESCRIPT "TYPE" WHERE TF IS UR TYPES??????????????

2024-09-28 13:32 UTC, anapiyani commented on src/pages/storage/accounting/_components/quantity-input/quantity-input.tsx
> +// const QuantitySelector = () => {
HOLE PAGE IS COMMENTS TF?

2024-09-28 13:33 UTC, anapiyani commented on src/pages/storage/accounting/_components/quantity-input/quantity-input.tsx
> +
NO TYPE? U COULD JUST WRITE THE TYPE <number> BROOOO

2024-09-28 13:33 UTC, anapiyani commented on src/pages/storage/accounting/_components/quantity-input/quantity-input.tsx
> +      {/* <p>+</p> */}
huh? comment

2024-09-28 13:33 UTC, anapiyani commented on src/pages/storage/accounting/_components/quantity-input/styles.module.scss
> +  //   width: 40px;
why comment styles?

2024-09-28 13:34 UTC, anapiyani commented on src/pages/storage/accounting/_components/table1/styles.module.scss
> +    //   }
rm comments

2024-09-28 13:34 UTC, anapiyani commented on src/pages/storage/accounting/_components/table1/styles.module.scss
> +          text-align: left; /* Align text to the left in nested table */
comment

2024-09-28 13:34 UTC, anapiyani commented on src/pages/storage/accounting/_components/table1/styles.module.scss
> +//     box-shadow: 0 0 12px rgba(21, 21, 21, 0.08), 0 2px 8px rgba(21, 21, 21, 0.08);
comments

2024-09-28 13:34 UTC, anapiyani commented on src/pages/storage/accounting/_components/table1/table1.tsx
> +            <Box sx={{ borderRadius: "8px", border: "0.1rem solid var(--neutral-300)" }}>
box to div and sx to classes styles

2024-09-28 13:34 UTC, anapiyani commented on src/pages/storage/accounting/_components/table2/styles.module.scss
> +          text-align: left; /* Align text to the left in nested table */
comment

2024-09-28 13:34 UTC, anapiyani commented on src/pages/storage/accounting/_components/table2/styles.module.scss
> +//     border-radius: 8px;
HOLE SCSS FILE IS COMMENT RM THEM

2024-09-28 13:35 UTC, anapiyani commented on src/pages/storage/accounting/_components/table2/table2.tsx
> +                padding: "0.8rem",
TOO MANY STYLES, TRY TO ADD CLASS TO IT AND WRITE IN SCSS

2024-09-28 13:36 UTC, anapiyani commented on src/pages/storage/accounting/_components/table3/table3.tsx
> +import AddIcon from '@mui/icons-material/Add';
ICONS.
Icons all should be in one import.
Import them all together.
EXAMPLE: 
import {
  CalendarMonth,
  CreditCard,
  HomeOutlined,
  ImportExport,
  LocalActivity,
  LocalAtm,
  MenuBook,
  North,
  Payments,
  Public,
  South,
} from "@mui/icons-material";

2024-09-28 13:37 UTC, anapiyani commented on src/pages/storage/accounting/_components/table3/table3.tsx
> +        category: "",
THIS IS TYPESCRIPT NOT A JSX WRITE THE TYPES FOR IT

2024-09-28 13:37 UTC, anapiyani commented on src/pages/storage/accounting/_components/table3/table3.tsx
> +                    // employeeData
TF IS THIS?

2024-09-28 13:37 UTC, anapiyani commented on src/pages/storage/accounting/_components/table4/styles.module.scss
> +// .table-container {
ONG AGAIN COMMENTS

2024-09-28 13:38 UTC, anapiyani commented on src/pages/storage/accounting/_components/table5/styles.module.scss
> +        }
DONT FORGET THIS ONE

2024-09-28 13:38 UTC, anapiyani commented on src/pages/storage/accounting/_components/table5/table5.tsx
> +    const [formData, setFormData] = useState({
TYPES FOR THEM

2024-09-28 13:38 UTC, anapiyani commented on src/pages/storage/accounting/_components/table5/table5.tsx
> +import LocalOfferIcon from '@mui/icons-material/LocalOffer';
WRITE ICONS IN ONE IMPORT IN ALL PAGES U DID

2024-09-28 13:39 UTC, anapiyani commented on src/pages/storage/accounting/_components/table5/table5.tsx
> +    const handleFormDataChange = (field: keyof ISearchFormData, value: any) => {
VALUE: ANY

WRITE TYPE FOR VALUE

2024-09-28 13:39 UTC, anapiyani commented on src/pages/storage/accounting/_components/table5/table5.tsx
> +        event: React.ChangeEvent<unknown>,
UNKNOWN? SEARCH FOR IT AND WRITE TYPE

2024-09-28 13:39 UTC, anapiyani commented on src/pages/storage/accounting/_components/table5/table5.tsx
> +                }
TF IS THIS?

2024-09-28 13:39 UTC, anapiyani commented on src/pages/storage/accounting/_components/table6/styles.module.scss
> +//     border-radius: 8px;
COMMENTS

2024-09-28 13:39 UTC, anapiyani commented on src/pages/storage/accounting/_components/table6/table6.tsx
> +import CloseIcon from '@mui/icons-material/Close';
ICONS IN ONE IMPORT

2024-09-28 13:40 UTC, anapiyani commented on src/pages/storage/accounting/_components/table7/table7.tsx
> +    const [formData, setFormData] = useState({
TYPES FOR THEM (WHY TF UR PAGES ARE SAME??????) WHY DONT USE COMPONENTS?????

2024-09-28 13:40 UTC, anapiyani commented on src/pages/storage/accounting/_components/table7/table7.tsx
> +    const handleFormDataChange = (field: keyof ISearchFormData, value: any) => {
ANY????? TYPE

2024-09-28 13:41 UTC, anapiyani commented on src/pages/storage/accounting/_components/table7/table7.tsx
> +        event: React.ChangeEvent<unknown>,
UNKNOWN???????????????

2024-09-28 13:41 UTC, anapiyani commented on src/pages/storage/accounting/_components/table7/table7.tsx
> +                    //   ? Math.ceil(employeeData.count / formData.page_size)
TF?

2024-09-28 13:42 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +import Table4 from "./_components/table4/table4";
OMGGGGG TF IS THISSSS??????????????? WHY TF 
ALL TABLES ARE SAME (DELETE THEM ALL AND WRITE A ONE COMPONENT TABLE AND CHANGE IT ) ALL TABLES ARE SAME THO?

2024-09-28 13:42 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +import CreateIcon from '@mui/icons-material/Create';
ALL ICONS SHOULD BE IMPORTED TOGETHER

2024-09-28 13:42 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    const tabs = [
WHERE IS TYPE OF THIS ARRAY?

2024-09-28 13:43 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    const [formData, setFormData] = useState({
WHERE TF IS TYPE OF FORMDATA????

2024-09-28 13:43 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    const [isLoading, setIsLoading] = useState(true);
NO TYPE

2024-09-28 13:43 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    const [currentTab, setCurrentTab] = useState(0);
TYPE

2024-09-28 13:43 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    const [hasParameters, setHasParameters] = useState(false);
AGAIN ITS TSX NOT JSX

2024-09-28 13:44 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +        getSearchResults(formData).then((data) => setSearchResults(data));
HUH??? WHY R U DOING THE REQUEST HERE???? U SHOULD DO IT IN HOOK FILE.

2024-09-28 13:44 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    function handleAutocompleteChange(value: any, fieldName: string): void {
ANY?? FR?

2024-09-28 13:44 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +    const handleFormDataChange = (field: keyof ISearchFormData, value: any) => {
ANY AGAIN

2024-09-28 13:45 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +      event: React.ChangeEvent<unknown>,
UNKNOWN SHOULD BE ONE TYPE THO

2024-09-28 13:45 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +          <div/>
TF IS THIS PIECE OF SHIT BRO

2024-09-28 13:45 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +                          <TreeView
TF IS BACKEND AND DND?

2024-09-28 13:46 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +                          sx={{ fontSize: "1.6rem", fontWeight: "400" }}
U COULD ADD CLASSNAME AND WRITE STYLES IN STYLES.MODULE.SCSS. TOO MCCJ STYLES HERE

2024-09-28 13:47 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +                          <br></br><br></br>
NEVER USE <BR/> LIKE THIS ADD STYLES.

DELETE THIS PART AND REWRITE. AT LEAST ONE <BR> AFTER SPACE

2024-09-28 13:47 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +                      <Table2/>
TABLE 2? FR DELETE TABLES AND CREATE ONE. THAT GETS PROPS AND RETURN VALUE NOT A FUCLIN 777777 TABLES

2024-09-28 13:48 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +                <Button
WHERE TF IS ONCLICK? DO NOT COMMENT BETTER DELETE

2024-09-28 13:48 UTC, anapiyani commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +            return <div></div>;
WHERE IS DEFAULT? AT LEAST SHOULD BE NOT FOUND TEXT

2024-09-28 13:48 UTC, anapiyani commented on src/pages/storage/accounting/styles.module.scss
> +    // border: 1px solid #e0e0e0;
DELETE COMMENTS

2024-09-28 13:49 UTC, anapiyani commented on src/pages/storage/accounting/styles.module.scss
> +    &__supplier {
DELETE COMMENTS

2024-09-28 13:49 UTC, anapiyani commented on src/pages/storage/accounting/styles.module.scss
> +    background-color: #ffffff;
DELETE COMMENTS

2024-09-28 13:50 UTC, anapiyani commented on src/pages/storage/storate.page.tsx
>                    Поскольку в каждом салоне красоты своя скорость расходования
Возьми каждого абзаца в p и просто дай стили margin-bottom: 1rem
delete the brs

2024-09-28 13:54 UTC, anapiyani requested changes
_download prettier and enable prettier when u save files._
**delete comments**
**do not forget types** it's not _JSX_ ITS **TYPESCRIPT**

**AND WHY TF U'VE CREATED 7 TABLES?????**
THEYR ALL SAME.
DELETE THEM CREATE ONE (IF ITS NOT A SAME THEN JUST SEND PROPS TO CHANGE THE TABLES)

CLEAR THE CODE

**LOGICS R NOT GOOD**
**_UR 50% OF COMPONENTS ARE COMMENTS AND ALL OF THEM R SAME._** THATS WHY UR CODING. SHOULD NOT REPEAT.

2024-09-29 08:37 UTC, Yangdux commented on src/components/search-filter-card/search-filter-card.tsx
> +// export default SearchFilterCard;
have reworked code with Zhango and returned code to the initial state, also deleted all comments

2024-09-29 09:17 UTC, Yangdux commented on src/pages/employees/salary/_components/step-input/step-input.component.tsx
> +      <p style={labelLength}>{labelName}</p>
writing <p labelLength && (style={labelLength})>{labelName}<p/> throws several errors, so I have changed it to 
<p style={labelLength ? labelLength : undefined}>{labelName}</p>. Dont know if it is correct or not

2024-10-01 12:10 UTC, Yangdux commented on src/pages/storage/accounting/storage-accounting.page.tsx
> +                          <TreeView
I copied this thing from another file, since it is similar component. But since i did not do anything in back it remained untouched and is not relevant to the actual functionality

2024-10-02 08:26 UTC, merged